export {default as NavBar} from './navbar/NavBar'
export {default as Footer} from './footer/Footer'
export {default as Slider} from './slider/Slider'
export {default as Rewards} from './homeCom/rewards/Rewards'
export {default as Membership} from './homeCom/membership/Membership'
export {default as MembershipCard} from './membershipCard/MembershipCard'
